# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QUa68Y2xg59bkvxL02CAeHUPC357dKQj
"""

num1=input('Enter Frirst Number')
num2=input('Enter Second Number')

def Add(num1,num2):
 return num1 + num2

def subtract(num1,num2):
 return num1 - num2

def mulitply(num1,num2):
 return num1 * num2

def divide(num1,num2):
    return num1 / num2


def square(num1):
    return num1 ** 2

def power(num1,num2):
    return num1 ** num2

def square_root(num1):
    return num1 ** 0.5
